name: sofia_redux
channels:
  - defaults
  - astropy
dependencies:
  - astropy::astropy>=4.0
  - astropy::astroquery>=0.4.4
  - bottleneck>=1.3.1
  - cloudpickle>=1.6.0
  - configobj>=5
  - cycler>=0.10.0
  - dill>=0.3
  - graphviz>=2.40
  - joblib>=0.14.1
  - matplotlib>=3.3
  - more-itertools>=8.5.0
  - numba>=0.53.1
  - numpy>=1.20.0
  - pandas>=1.3
  - photutils>=0.7.2
  - pip>=20.3
  - psutil>=5.8.0
  - pyqt>=5.9.2
  - pytest>=5.3.5
  - pytest-astropy>=0.8.0
  - pytest-astropy-header>=0.1.2
  - pytest-cov>=2.8.1
  - pytest-mock>=1.13.0
  - conda-forge::pytest-qt<4
  - pytest-remotedata>=0.3.2
  - pytest-timeout>=1.3.3
  - python>=3.8
  - regex>=2021.4.4
  - scikit-image<0.19
  - scikit-learn>=0.22.1
  - scipy>=1.4.1
  - sphinx-astropy>=1.2
  - pip:
    - mimeparse>=0.1

